name = "vtecgroup"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "dist/index.js"
compatibility_date = "2024-12-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[build.upload]
format = "modules"
main = "dist/index.js"

[env.production]
routes = [
  { pattern = "vtecgroup.co.ke/*", zone_id = "" }
]

[[env.production.kv_namespaces]]
binding = "KV"
id = ""
