/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessDiagnosticRouteImport } from './routes/business-diagnostic'
import { Route as AiDiagnosticInfoRouteImport } from './routes/ai-diagnostic-info'
import { Route as IndexRouteImport } from './routes/index'

const BusinessDiagnosticRoute = BusinessDiagnosticRouteImport.update({
  id: '/business-diagnostic',
  path: '/business-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDiagnosticInfoRoute = AiDiagnosticInfoRouteImport.update({
  id: '/ai-diagnostic-info',
  path: '/ai-diagnostic-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-diagnostic-info' | '/business-diagnostic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-diagnostic-info' | '/business-diagnostic'
  id: '__root__' | '/' | '/ai-diagnostic-info' | '/business-diagnostic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDiagnosticInfoRoute: typeof AiDiagnosticInfoRoute
  BusinessDiagnosticRoute: typeof BusinessDiagnosticRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/business-diagnostic': {
      id: '/business-diagnostic'
      path: '/business-diagnostic'
      fullPath: '/business-diagnostic'
      preLoaderRoute: typeof BusinessDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-diagnostic-info': {
      id: '/ai-diagnostic-info'
      path: '/ai-diagnostic-info'
      fullPath: '/ai-diagnostic-info'
      preLoaderRoute: typeof AiDiagnosticInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDiagnosticInfoRoute: AiDiagnosticInfoRoute,
  BusinessDiagnosticRoute: BusinessDiagnosticRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
