/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BusinessDiagnosticRouteImport } from './routes/business-diagnostic'
import { Route as AiDiagnosticInfoRouteImport } from './routes/ai-diagnostic-info'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDiagnosticRouteImport } from './routes/api/diagnostic'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const BusinessDiagnosticRoute = BusinessDiagnosticRouteImport.update({
  id: '/business-diagnostic',
  path: '/business-diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDiagnosticInfoRoute = AiDiagnosticInfoRouteImport.update({
  id: '/ai-diagnostic-info',
  path: '/ai-diagnostic-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagnosticRoute = ApiDiagnosticRouteImport.update({
  id: '/api/diagnostic',
  path: '/api/diagnostic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-diagnostic-info': typeof AiDiagnosticInfoRoute
  '/business-diagnostic': typeof BusinessDiagnosticRoute
  '/api/chat': typeof ApiChatRoute
  '/api/diagnostic': typeof ApiDiagnosticRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-diagnostic-info'
    | '/business-diagnostic'
    | '/api/chat'
    | '/api/diagnostic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-diagnostic-info'
    | '/business-diagnostic'
    | '/api/chat'
    | '/api/diagnostic'
  id:
    | '__root__'
    | '/'
    | '/ai-diagnostic-info'
    | '/business-diagnostic'
    | '/api/chat'
    | '/api/diagnostic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDiagnosticInfoRoute: typeof AiDiagnosticInfoRoute
  BusinessDiagnosticRoute: typeof BusinessDiagnosticRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDiagnosticRoute: typeof ApiDiagnosticRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/business-diagnostic': {
      id: '/business-diagnostic'
      path: '/business-diagnostic'
      fullPath: '/business-diagnostic'
      preLoaderRoute: typeof BusinessDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-diagnostic-info': {
      id: '/ai-diagnostic-info'
      path: '/ai-diagnostic-info'
      fullPath: '/ai-diagnostic-info'
      preLoaderRoute: typeof AiDiagnosticInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagnostic': {
      id: '/api/diagnostic'
      path: '/api/diagnostic'
      fullPath: '/api/diagnostic'
      preLoaderRoute: typeof ApiDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDiagnosticInfoRoute: AiDiagnosticInfoRoute,
  BusinessDiagnosticRoute: BusinessDiagnosticRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDiagnosticRoute: ApiDiagnosticRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
